### ISSUE TITLE
Uncertainties per sample in yield tables

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/cabinetry#191]
The current yield table implementation (after #158) does not include a calculation of yield uncertainties per sample. These numbers can be more difficult to interpret due to correlations between samples, but would nevertheless be useful to provide. Additional calculations are required to obtain these uncertainties, so they may be implemented as optional.

**Comment by Daniel-Noel** [comment]
Hi Alex, thanks for the yield table implementation! Including the calculations of uncertainties per sample would be very useful for writing out a full table in a similar style to HistFitter.

**Comment by alexander-held** [comment]
#356 adds per-sample yield uncertainties. It was possible to calculate per-sample yield uncertainties previously in a more manual way by pruning samples from the model and performing the calculations with single-sample models. There is one important difference between what this calculation does compared to what #356 implements, which is described in #357. The pre-fit `staterror` treatment is more intuitive in this manual pruning approach, while the current implementation in #356 is aligned with the post-fit calculation method.
