### ISSUE TITLE
Releases on conda-forge

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/cabinetry#283]
Many packages in the Scikit-HEP project provide releases on conda-forge. It would be good for `cabinetry` to do the same, especially that is it highly connected to `pyhf` and the latter is available there.

**Comment by matthewfeickert** [comment]
@alexander-held If you want to schedule a video call we can step through this together (not that you _need_ my help, but I found it helpful when Bradley Dice walked me through the process at SciPy 2020).

**Comment by alexander-held** [comment]
@matthewfeickert thanks, your help would be highly appreciated here! We can coordinate via Slack. I had a very brief look at `pyhf-feedstock` and was surprised how many files there are, but I guess some of these are auto-generated.

**Comment by eduardo-rodrigues** [comment]
(Folks, I created the issue so that this does not get forgotten, and since I thought about it, I wrote it down. But no sense of pressure from me at all. Just deal with this in due time for you.)
