### ISSUE TITLE
Crashes when calculating upper limits

### ISSUE THREAD

**Issue by miholzbo** [scikit-hep/cabinetry#495]
Hi,

I see some crashes when using `cabinetry.fit.limit(...)` which confuse me a bit. As you can see in the stack below, the observed CLs values can be calculated and things crash when moving to the expected limits.

It's somewhat clear that the problem originates when re-deriving the left- and right  "bracket" in the part [here](https://github.com/scikit-hep/cabinetry/blob/master/src/cabinetry/fit/__init__.py#L997-L1020). For some reason the left and right is set to both 0.1 - that's a bit confusing because the scan of the observed CLs values yielded values both above and below 0.05, i.e. the initial scan range should be chosen somewhat reasonable.

```
INFO - cabinetry.fit - calculating 95% confidence level upper limit for mu_Signal_ED_2000_1p0_run2
INFO - cabinetry.fit - determining observed upper limit
DEBUG - cabinetry.fit - mu_Signal_ED_2000_1p0_run2 = 0.1000, observed CLs = 0.1657
DEBUG - cabinetry.fit - mu_Signal_ED_2000_1p0_run2 = 10.0000, observed CLs = 0.0000
DEBUG - cabinetry.fit - mu_Signal_ED_2000_1p0_run2 = 7.0126, observed CLs = 0.0000
DEBUG - cabinetry.fit - mu_Signal_ED_2000_1p0_run2 = 3.5563, observed CLs = 0.0000
DEBUG - cabinetry.fit - mu_Signal_ED_2000_1p0_run2 = 1.8281, observed CLs = 0.0000
DEBUG - cabinetry.fit - mu_Signal_ED_2000_1p0_run2 = 0.9641, observed CLs = 0.0000
DEBUG - cabinetry.fit - mu_Signal_ED_2000_1p0_run2 = 0.5320, observed CLs = 0.0000
DEBUG - cabinetry.fit - mu_Signal_ED_2000_1p0_run2 = 0.3160, observed CLs = 0.0004
DEBUG - cabinetry.fit - mu_Signal_ED_2000_1p0_run2 = 0.2080, observed CLs = 0.0111
DEBUG - cabinetry.fit - mu_Signal_ED_2000_1p0_run2 = 0.1540, observed CLs = 0.0467
DEBUG - cabinetry.fit - mu_Signal_ED_2000_1p0_run2 = 0.1490, observed CLs = 0.0529
INFO - cabinetry.fit - successfully converged after 11 steps
INFO - cabinetry.fit - observed upper limit: 0.1490
INFO - cabinetry.fit - determining expected -2 sigma upper limit
DEBUG - cabinetry.fit - mu_Signal_ED_2000_1p0_run2 = 0.1000, expected -2 sigma CLs = 0.0321 (cached)
DEBUG - cabinetry.fit - mu_Signal_ED_2000_1p0_run2 = 0.1000, expected -2 sigma CLs = 0.0321 (cached)
ERROR - cabinetry.fit - CLs values at 0.1000 and 0.1000 do not bracket CLs=0.0500, try a different starting bracket
Traceback (most recent call last):
  File "/home/miholzbo/Code/LJAnalysis/UpperLimits.py", line 27, in <module>
    results_limit = cabinetry.fit.limit(model, data, poi_name="mu_Signal_ED_2000_1p0_run2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miholzbo/Code/LJStatAnalysis/.venv/lib/python3.11/site-packages/cabinetry/fit/__init__.py", line 971, in limit
    res = scipy.optimize.root_scalar(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_106a_ATLAS_2/x86_64-el9-gcc13-opt/lib/python3.11/site-packages/scipy/optimize/_root_scalar.py", line 279, in root_scalar
    r, sol = methodc(f, a, b, args=args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_106a_ATLAS_2/x86_64-el9-gcc13-opt/lib/python3.11/site-packages/scipy/optimize/_zeros_py.py", line 806, in brentq
    r = _zeros._brentq(f, a, b, xtol, rtol, maxiter, args, full_output, disp)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: f(a) and f(b) must have different signs
```

When looking into this, I've also noticed that the upper limit scan cabinetry does seem to me absurdly slow and the naive pyhf version via

```python
poi_vals = np.linspace(0.05, 1.0, 10)
poi_vals = (0.1, 0.5, 2)
results = [
     pyhf.infer.hypotest(
         test_poi, data, model, test_stat="qtilde", return_expected_set=True
     )
     for test_poi in poi_vals
]
```
is much faster although the underlying function is `pyhf.infer.hypotest()` in both cases. Cabinetry seems manually run the 5 expected calculations (nominal, +/- 1 sigma,  +/- 2 sigma) again instead of using the values that you get when running with `return_expected_set=True`. Is there a particular reason for this?

Thanks!
Michael

**Comment by alexander-held** [comment]
Hi Michael, I think there are a few different points here.

**Why does it crash?**
It comes down to this line
```
ERROR - cabinetry.fit - CLs values at 0.1000 and 0.1000 do not bracket CLs=0.0500, try a different starting bracket
```
which might be a bit confusing in this specific case. The default lower bound for the bracket used to find CLs=0.05 crossings is a POI value of 0.1, but this can be changed via the `bracket` keyword argument (see https://cabinetry.readthedocs.io/en/latest/api.html#cabinetry.fit.limit). The algorithm used here requires the specification of a bracket that encloses the final value. I initially also tried a different algorithm but that had very mixed success when exceeding the starting bracket and overall performed worse. At the moment this is therefore a hard requirement and the code doesn't try to recover. What happens here is that the lowest possible value for the POI of 0.1 (as specified by the bracket) is already too high to find the CLs=0.05 crossing (given that the CLs at this point is already dropped lower, down to 0.0321). It tries the same value again (which I think is acting as upper bound estimated from the code you linked, but given that it is using the cached result it spends no significant time on that). Then the algorithm determines it will not find the crossing within the given bracket and fails.

The solution here is to change the `bracket` to allow lower values. When setting the default values I investigated setting the default lower bound to 0.01, which unfortunately made some other limits of O(1) much slower to converge. This is overall certainly an area where algorithmic improvements could help, ideas are welcome!

Differences between observed and expected limits can happen, in this case we already see a fairly big difference at a POI value of 0.1:
```
DEBUG - cabinetry.fit - mu_Signal_ED_2000_1p0_run2 = 0.1000, observed CLs = 0.1657
DEBUG - cabinetry.fit - mu_Signal_ED_2000_1p0_run2 = 0.1000, expected -2 sigma CLs = 0.0321 (cached)
```
There is no guarantee that if any of the specific crossings are found, the rest can be found as well.

**How does this differ from pyhf?**
The code you link does the same types of fits as well, but on a fixed grid. It will do this 10 times in your example where there are 10 POI values to check. This can give you an idea for where the actual CLs=0.05 crossing lie (if you have two POIs evaluated that bracket the CLs=0.05 point from above and below) but your resolution is limited by the resolution of the grid.

`cabinetry` has a different approach here and uses Brent's algorithm for finding the actual crossing point with a configurable tolerance in POI values (`poi_tolerance`, defaults to 0.01). This should generally give you a more reliable estimate of the actual crossing point and does so in an automated fashion as long as the starting bracket is suitable for the problem. You can speed this up by decreasing `poi_tolerance`, which means the algorithm can stop earlier. There's also a `maxsteps` setting to limit the number of steps taken to find the crossing.

At the moment this algorithm runs for the observed, expected as well as the +/- 1 and 2 sigma bands. It keeps using information from all previous fits, but this is not necessarily extremely helpful if the tolerance is low, given that most fits will then take place very close to the target POI value and somewhat far away from the places where the bands end up crossing instead.

**Could this be made faster?**
Yes, there is definitely room for good ideas. We could do the search for the POI value in log space, which I heard as a recommendation, but haven't seen much of an impact with this specific algorithm used here for the models I tried. Other algorithms can also be tried of course. The biggest benefit would probably come from injecting some knowledge about the CLs distribution back into the algorithm to make more informed guesses for the best next point to probe.

**Comment by alexander-held** [comment]
It might also be interesting to compare to [`pyhf.infer.intervals.upper_limits.toms748_scan`](https://pyhf.readthedocs.io/en/v0.7.6/_generated/pyhf.infer.intervals.upper_limits.toms748_scan.html#pyhf.infer.intervals.upper_limits.toms748_scan) for your case. That didn't exist initially when `cabinetry.fit.limit` was written but uses a similar approach to find the crossing with `toms748` in `scipy`.
